/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#005127',
        'primary-container': '#1a6b3a',
        'on-primary': '#ffffff',
        'on-primary-container': '#99e9ab',
        'primary-fixed': '#a4f4b6',
        'primary-fixed-dim': '#89d89c',
        'on-primary-fixed': '#00210c',
        'on-primary-fixed-variant': '#005228',
        'inverse-primary': '#89d89c',

        secondary: '#5d5f5f',
        'on-secondary': '#ffffff',
        'secondary-container': '#dfe0e0',
        'on-secondary-container': '#616363',
        'secondary-fixed': '#e2e2e2',
        'secondary-fixed-dim': '#c6c6c7',
        'on-secondary-fixed': '#1a1c1c',
        'on-secondary-fixed-variant': '#454747',

        tertiary: '#5c4200',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#7a5800',
        'on-tertiary-container': '#ffd17a',
        'tertiary-fixed': '#ffdea5',
        'tertiary-fixed-dim': '#f7bd44',
        'on-tertiary-fixed': '#261900',
        'on-tertiary-fixed-variant': '#5d4200',

        gold: '#C9951A',

        surface: '#f8f9ff',
        'surface-dim': '#d1dbec',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eef4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dfe9fa',
        'surface-container-highest': '#d9e3f4',
        'surface-tint': '#1b6c3b',
        'surface-variant': '#d9e3f4',
        'on-surface': '#121c28',
        'on-surface-variant': '#404940',
        'inverse-surface': '#27313e',
        'inverse-on-surface': '#eaf1ff',

        outline: '#707a6f',
        'outline-variant': '#bfc9bd',

        background: '#f8f9ff',
        'on-background': '#121c28',

        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      fontSize: {
        display:      ['64px', { lineHeight: '1.02', fontWeight: '900', letterSpacing: '-0.025em' }],
        'display-sm': ['40px', { lineHeight: '1.05', fontWeight: '900', letterSpacing: '-0.02em' }],
        h1:           ['32px', { lineHeight: '1.15', fontWeight: '700', letterSpacing: '-0.01em' }],
        h2:           ['24px', { lineHeight: '1.25', fontWeight: '700' }],
        h3:           ['18px', { lineHeight: '1.35', fontWeight: '600' }],
        'body-lg':    ['17px', { lineHeight: '1.6',  fontWeight: '400' }],
        body:         ['15px', { lineHeight: '1.55', fontWeight: '400' }],
        'body-sm':    ['13px', { lineHeight: '1.5',  fontWeight: '400' }],
        label:        ['11px', { lineHeight: '1',    fontWeight: '700', letterSpacing: '0.08em' }],
        price:        ['22px', { lineHeight: '1',    fontWeight: '700' }],
        'price-lg':   ['28px', { lineHeight: '1',    fontWeight: '800' }],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '12px',
        base: '8px',
        md: '24px',
        lg: '40px',
        xl: '64px',
        gutter: '24px',
        section: '80px',
        'section-mobile': '56px',
        'section-tight': '48px',
        'section-tight-mobile': '32px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      boxShadow: {
        card: '0px 2px 4px rgba(0,0,0,0.05)',
        'card-hover': '0px 4px 12px rgba(0,0,0,0.10)',
      },
    },
  },
  plugins: [],
}
